name: Release
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create Release Zip
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'FS25_ReverseGear.zip'
          exclusions: '/.git* .git* .editorconfig README.md LICENSE icon_ReverseGear.png /eng/*'
      - name: Upload Zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./FS25_ReverseGear.zip
